config/routes.rb
Rails.application.routes.draw do
  resources :people, except: [:show]

  root to: "people#index"
  
  get 'people/index' => 'people#index'

  get 'people/new' => 'people#new'

  get 'people/create'

  get 'people/edit'

  get 'people/update'

  get 'people/destroy'

  get "dashboard/:page" => "dashboard#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person
  include Mongoid::Document
  field :firstName, type: String
  field :lastName, type: String
  field :email, type: String
  field :notes, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def show
        if valid_page?
            render template: "dashboard/#{params[:page]}"
        else
            render file: "public/404.html", status: :not_found
        end
    end
    private
    def valid_page?
      File.exist?(Pathname.new(Rails.root + "app/views/dashboard/#{params[:page]}.html.erb"))
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      redirect_to people_path, notice: "The person has been created!" and return
    end
    render 'new'
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])

    if @person.update_attributes(person_params)
      redirect_to people_path, notice: "#{@person.firstName} #{@person.lastName} has been updated!" and return
    end

    render 'edit'
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to people_path, notice: "#{@person.firstName} #{@person.lastName} has been deleted!" and return
  end
  
  private
  def person_params
    params.require(:person).permit(:firstName, :lastName, :email, :notes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/dashboard/about.html.erb
<h2>About page</h2>

<p>This is your about page!!!</p>

app/views/dashboard/home.html.erb
<div class="row">
    <div class="col-lg-12">
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="#">Hidden brand</a>
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </div>
</div>
<p>This would be a static home page in a Rails application.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MongoDBExampleApp</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f|%>
    <div class="form-group">
        <%= f.label :firstName%>
        <%= f.text_field :firstName, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :lastName%>
        <%= f.text_field :lastName, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.label :notes %>
        <%= f.text_area :notes, class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/people/create.html.erb
<h1>People#create</h1>
<p>Find me in app/views/people/create.html.erb</p>

app/views/people/destroy.html.erb
<h1>People#destroy</h1>
<p>Find me in app/views/people/destroy.html.erb</p>

app/views/people/edit.html.erb
<h1>New Person</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/people/index.html.erb
<h1>People</h1>
<div class="well">
  <%= link_to "New Person", new_person_path, class: "btn btn-primary" %>
</div>

<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Notes</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% if @people.size == 0 %>
      <tr>
        <td colspan="6">No people found.</td>
      </tr>
    <% else %>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.firstName %></td>
          <td><%= person.lastName %></td>
          <td><%= person.email %></td>
          <td><%= person.notes %></td>
          <td>
            <%= link_to "Edit", edit_person_path(person), class: "btn btn-default" %>
          </td>
          <td>
            <%= button_to "Delete", person, method: :delete, data: { confirm: "Are you sure you wish to delete #{person.firstName} #{person.lastName}?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/people/new.html.erb
<h1>New Person</h1>
<div class="well">
  <%= render "form" %>
</div>

app/views/people/update.html.erb
<h1>People#update</h1>
<p>Find me in app/views/people/update.html.erb</p>